### ISSUE TITLE
Subscribing To API

### ISSUE THREAD

**Issue by jasonagnew** [hmrc/your-tax-calculator#15]
Perhaps I'm missing something but it doesn't appear possible to subscribe to this API. On https://developer.service.hmrc.gov.uk/developer/applications/xxxx-xxx-xxx-xxx even if you subscribe to everything you still can't access this.

```
curl -H 'Authorization: Bearer [SERVER_TOKEN]' \
-H 'Accept: application/vnd.hmrc.1.0+json' \
'https://api.service.hmrc.gov.uk/your-tax-calculator/tax-calc/calculate-tax/false/2016-17/1100T/4000000/annual'
```

Returns
```
{ "code" : "RESOURCE_FORBIDDEN", "message" : "The application is not subscribed to the API which it is attempting to invoke" }
```

Thanks

**Comment by Trojanater** [comment]
This repo has been decommissioned and replaced by https://github.com/hmrc/paye-estimator
